name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/app/requirements.txt
        pip install -r tests/requirements.txt
    - name: Run unit tests
      run: pytest tests/unit

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/app/requirements.txt
        pip install -r tests/requirements.txt
    - name: Run integration tests
      run: pytest tests/integration

  end-to-end-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/app/requirements.txt
        pip install -r tests/requirements.txt
    - name: Run end-to-end tests
      run: behave tests/end-2-end

  deploy-to-dev:
    needs: end-to-end-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        run: echo "docker/login-action@v1"
      - name: Build and push Docker image
        run: echo "Replace with docker push to yourusername/yourrepositoryname:yourtag docker/build-push-action@v2"
